name: Create PDF slides
on:
  push:
    tags:
      - '*'

jobs:
  create-pdf-slides:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Debug
        run: ls -la "${{ github.workspace }}"
      - name: Can we run docker commands?
        run: docker run --rm -e MARP_USER="$(id -u):$(id -g)" -v "${{ github.workspace }}/presentation:/home/marp/app" marpteam/marp-cli:main --allow-local-files --theme-set vorlesung.css --pdf -I . -o slides/
      - name: List the results
        run: ls -la ${{ github.workspace }}/presentation/slides
      - name: Release slides
        run: gh release create -d $GITHUB_REF_NAME presentation/slides/*.pdf
        env:
          GH_TOKEN: ${{ github.token }}